[build]
builder = "nixpacks"
buildCommand = "npm install -g vercel && pip install -r requirements.txt"

[deploy]
startCommand = "export PATH=$PATH:/usr/local/bin:/root/.npm-global/bin && python main.py"
